name: GitHub Pages deploy

on:
  push:
    branches:
      - main

jobs:
  checkout-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: cd frontend && npm i
        shell: bash
      - run: cd frontend && npm ci
        shell: bash
      - run: cd frontend && npm run build
        shell: bash
      - name: Deploy
        if: success()
        uses: Cecilapp/GitHub-Pages-deploy@2.0.1
        env:
          EMAIL: juanfkurucz@gmail.com
          GH_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BUILD_DIR: frontend/build/
